export const runtime = "nodejs";
import nodemailer from "nodemailer";
import { NextResponse, NextRequest } from "next/server";

interface Message {
  type: "user" | "ai";
  content: string;
  timestamp: string;
}

export async function POST(request: NextRequest) {
  try {
    const { clientEmail, messages } = await request.json();

    if (!clientEmail || !messages?.length) {
      return NextResponse.json({ error: "Missing email or messages" }, { status: 400 });
    }

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || "smtp.gmail.com",
      port: Number(process.env.SMTP_PORT) || 587,
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    const subject = `Your EVO AI Chat Transcript · ${new Date().toDateString()}`;
    const from = `"EVO AI · Beelockchain" <${process.env.SMTP_USER}>`;

    const html = `
      <div style="font-family:Arial,sans-serif;background:#0d0d0d;padding:30px;">
        <div style="max-width:600px;margin:auto;background:#111;border-radius:16px;overflow:hidden;border:1px solid #222;">
          <div style="background:linear-gradient(135deg,#00bfa5,#00838f);padding:24px;text-align:center;">
            <h2 style="margin:0;color:#fff;font-size:20px;">EVO AI · Chat Transcript</h2>
            <p style="margin:6px 0 0;color:rgba(255,255,255,0.75);font-size:12px;">${new Date().toDateString()}</p>
          </div>
          <div style="padding:24px;">
            ${messages.map((m: Message) => {
              const isUser = m.type === "user";
              const time = new Date(m.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
              return `
                <div style="margin-bottom:16px;text-align:${isUser ? "right" : "left"};">
                  <div style="display:inline-block;max-width:75%;background:${isUser ? "#00bfa5" : "#1a1a1a"};color:${isUser ? "#fff" : "#ddd"};border-radius:12px;padding:12px 16px;font-size:13px;line-height:1.6;">
                    <div style="font-size:10px;opacity:0.6;margin-bottom:4px;">${isUser ? "You" : "EVO AI"} · ${time}</div>
                    ${m.content.replace(/\n/g, "<br/>")}
                  </div>
                </div>
              `;
            }).join("")}
          </div>
          <div style="padding:16px;text-align:center;border-top:1px solid #222;">
            <p style="margin:0;color:#555;font-size:11px;">Generated by EVO AI · Beelockchain</p>
          </div>
        </div>
      </div>
    `;

    await transporter.sendMail({ from, to: clientEmail, subject, html });
    await transporter.sendMail({ from, to: process.env.ADMIN_EMAIL, subject: `[Admin] ${subject} — from ${clientEmail}`, html });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Email send failed:", error);
    return NextResponse.json({ error: "Failed to send email" }, { status: 500 });
  }
}